# Main working (data) directory
data_dir: "/mnt/shared/scratch/vtelizhe/metagenomic_networks/01test"

# Sample design file
samples: "sample_design.txt"

# Input directories
input:
  long_reads: "nanopore"
  short_reads: "illumina"
  databases: "/mnt/shared/scratch/vtelizhe/metagenomic_networks/databases"

# Reference genome
reference:
  human: "human_genome/hg38.fa"

# Output directories
output:
  dehost: 
    sam: "nano_dehost"
    result: "result/dehost"
  assembly:
    spades: "hybrid_temp/spades"
    binning: "hybrid_temp/binning"
     
# Resources
threads:
  dehost: 20
  qc: 60
  spades: 16
  binning: 12
  refinement: 4
mem:
  dehost: "16G"
  qc: "16G"
  spades: "32G"
  binning: "125G"
  refinement: "64G"

# Tool-specific parameters
minimap2:
  options: "-ax map-ont"

seqkit:
  options: ""

metawrap:
  read_qc_options: "--skip-pre-qc-report --skip-post-qc-report"

spades:
  options: "--meta"
  threads: 12
  memory: 800
